spring:
  application:
    name: Config-Server-App

  cloud:
    config:
      server:
        git:
          uri: https://github.com/ashokitschool/configuration_properties

management:
  security:
    enabled: false
    
server:
  port: 8071