spring:
  application:
    name: Circuit-Breaker-ResillenceJ
    
server:
  port: 8088
  
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
        
  endpoint:
    health:
      show-details: always
      
  health:
    circuitbreakers:
      enabled: true
      
resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 30s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10